### ISSUE TITLE
MultiQC failure when summarising ICELL8 "barcodes" QC outputs

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#289]
The pipeline implemented in `process_icell.py` reports a failure when running `multiqc` on the outputs from the QC run on the 'barcodes' Fastqs.

The error comes from the `reportqc.py` utility:

    [INFO   ]         multiqc : This is MultiQC v1.0
    [INFO   ]         multiqc : Template    : default
    [INFO   ]         multiqc : Report title: XXXXXXXXXXXXXXXXXXXXXXX (fastqs.barcodes): QC report
    [INFO   ]         multiqc : Searching 'XXXXXXXXXXXXXXXXXXXXXXX/qc.barcodes'
    Searching 63376 files..
    [ERROR  ]         multiqc : Oops! The 'fastq_screen' MultiQC module broke... 
                        Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                        (if possible, include a log file that triggers the error) 
    ============================================================
    Module fastq_screen raised an exception: Traceback (most recent call last):
      File "XXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/EGG-INFO/scripts/multiqc", line 373, in multiqc
        output = mod()
      File "XXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/fastq_screen/fastq_screen.py", line 32, in __init__
        for f in self.find_log_files('fastq_screen', filehandles=True):
      File "XXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/base_module.py", line 66, in find_log_files
        with io.open (os.path.join(f['root'],f['fn']), "r", encoding='utf-8') as fh:
    MemoryError
    ============================================================
    [ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
                        Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                        (if possible, include a log file that triggers the error) 
    ============================================================
    Module fastqc raised an exception: Traceback (most recent call last):
      File "XXXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/EGG-INFO/scripts/multiqc", line 373, in multiqc
        output = mod()
       File "XXXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 42, in __init__
        for f in self.find_log_files('fastqc/data'):
      File "XXXXXXXXX/python/lib/python2.7/site-packages/multiqc-1.0-py2.7.egg/multiqc/modules/base_module.py", line 66, in find_log_files
        with io.open (os.path.join(f['root'],f['fn']), "r", encoding='utf-8') as fh:
    MemoryError
    ============================================================
    [WARNING]         multiqc : No analysis results found. Cleaning up..
    [INFO   ]         multiqc : MultiQC complete

An initial guess is that the number of result files (over 20,000) overwhelms the available resources for `multiqc`.

**Comment by pjbriggs** [comment]
MultiQC has been disabled for the barcode Fastqs in the ICELL8 pipeline, as part of PR #304.
