### ISSUE TITLE
Automatic reference documentation failure for 'export_to_galaxy.py' utility

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#373]
Building the reference documentation for the `export_to_galaxy.py` utility fails on ReadTheDocs:

    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/auto-process-ngs/envs/devel/bin/export_to_galaxy.py", line 4, in <module>
        __import__('pkg_resources').run_script('auto-process-ngs==0.17.0', 'export_to_galaxy.py')
      File "/home/docs/checkouts/readthedocs.org/user_builds/auto-process-ngs/envs/devel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/home/docs/checkouts/readthedocs.org/user_builds/auto-process-ngs/envs/devel/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
        exec(code, namespace, namespace)
      File "/home/docs/checkouts/readthedocs.org/user_builds/auto-process-ngs/envs/devel/lib/python2.7/site-packages/auto_process_ngs-0.17.0-py2.7.egg/EGG-INFO/scripts/export_to_galaxy.py", line 21, in <module>
        from auto_process_ngs.galaxy import build_library_directory
      File "/home/docs/checkouts/readthedocs.org/user_builds/auto-process-ngs/envs/devel/lib/python2.7/site-packages/auto_process_ngs-0.17.0-py2.7.egg/auto_process_ngs/galaxy.py", line 26, in <module>
        from bioblend import galaxy
    ImportError: No module named bioblend

See https://auto-process-ngs.readthedocs.io/en/devel/reference/utilities.html#export-to-galaxy-py

**Comment by pjbriggs** [comment]
`export_to_galaxy.py` has been removed by PR #380, which also addressed this issue.
