### ISSUE TITLE
'metadata' command crashes if run ID number is not an integer

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#491]
The `auto_process.py metadata` command fails if the `metadata.info` file contains a run ID number which is not an integer, for example:

    $ cat metadata.info
    ...snipped...
    instrument_run_number   BCLFiles

    $ auto_process.py metadata
    auto_process.py version 0.18.0
    Metadata in metadata.info:
    Traceback (most recent call last):
      File ".../bin/auto_process.py", line 8, in <module>
        main()
      File ".../auto_process_ngs/cli/auto_process.py", line 1526, in main
        commands[cmd](args)
      File ".../auto_process_ngs/cli/auto_process.py", line 1080, in metadata
        d.print_metadata()
      File ".../auto_process_ngs/auto_processor.py", line 797, in print_metadata
        self.print_values(self.metadata)
      File ".../auto_process_ngs/auto_processor.py", line 737, in print_values
        values['Run reference'] = self.run_reference_id
      File ".../auto_process_ngs/auto_processor.py", line 679, in run_reference_id
        facility_run_number=self.metadata.run_number)
      File ".../auto_process_ngs/analysis.py", line 1162, in run_reference_id
        run_number = int(run_number)
    ValueError: invalid literal for int() with base 10: 'BCLFiles'

**Comment by pjbriggs** [comment]
In the original error there was also an issue that the supplied run name was hitting an edge case in the run name splitter from `bcftbx/IlluminaData` (six character string incorrectly identified as a datestamp) which is fixed by PR https://github.com/fls-bioinformatics-core/genomics/pull/149.

**Comment by pjbriggs** [comment]
Fixed by PR #492.
