### ISSUE TITLE
'setup': failure when sample sheet contains trailing "empty" lines

### ISSUE THREAD

**Issue by pjbriggs** [fls-bioinformatics-core/auto_process_ngs#588]
The  `setup` command failed for a HiSeq run where the run data is held on a remote server.

The samplesheet exists on the remote server within the run, but `setup` seems to fail after acquiring it:

    Trying 'XXXXXX@XXXXXXXXX:/XXXXXX/XXXXXXXXXXXXXX/SampleSheet.csv'
    rsync -av -e ssh XXXXXX@XXXXXXXXX:/XXXXXX/XXXXXXXXXXXXXX/SampleSheet.csv  /XXXXXXX/.XXXXXXXX_analysis.bb0ab53b-b5ad-4b4c-ad20-6935d9e91ab3/tmp
    Copying original sample sheet to /XXXXXXX/.XXXXXXXX_analysis.bb0ab53b-b5ad-4b4c-ad20-6935d9e91ab3/SampleSheet.orig.csv
    CRITICAL:root:setup: Failed to acquire sample sheet: '<' not supported between instances of 'str' and 'int'

It's unclear if there's a problem with the `rsync`, with the samplesheet file, or something else.

**Comment by pjbriggs** [comment]
The error seems to be coming from within the sample sheet clean up operation:

    Traceback (most recent call last):
      File "XXXX/auto_process_ngs/commands/setup_cmd.py", line 196, in setup
        make_custom_sample_sheet(tmp_sample_sheet,custom_sample_sheet)
      File "XXXX/auto_process_ngs/bcl2fastq_utils.py", line 284, in make_custom_sample_sheet
        sample_sheet.data.sort(lambda line: line['Lane'])
      File "XXXX/bcftbx/TabFile.py", line 850, in sort
        self.__data = sorted(self.__data,key=sort_func,reverse=reverse)
    TypeError: '<' not supported between instances of 'str' and 'int'

which implies a problem with the specific sample sheet.

**Comment by pjbriggs** [comment]
Sample sheet has trailing lines of the form:

    ,,,,,,,,,,,
    ,,,,,,,,,,,

When these lines are removed then `setup` completes without further issues.

**Comment by pjbriggs** [comment]
This bug is specifically related to sample sheets which contain lane information, and appears to be raised in the `make_custom_samplesheet` function (which sorts the lines by lane, when present).

More generally however the underlying issue is that trailing empty lines should probably be ignored when the sample sheet file is read into a `SampleSheet` instance; this PR in the `genomics-bcftbx` package is intended to fix that problem https://github.com/fls-bioinformatics-core/genomics/pull/171
